version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - type: volume
        source: movies_db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - static_volume:/static
    expose:
      - "8080"
    depends_on:
      - db
    restart: always
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/static:ro
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
volumes:
  static_volume:
  movies_db:
    external: true